spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7

    #ollama:
      #base-url: "disabled"

  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.ollama.OllamaAutoConfiguration
#Here we are using exclude concept to exclude the auto-configuration of ollama, because we are using openai, if we don't exclude it then it will try to auto-configure ollama and since we have not provided the configuration for ollama it will throw exception, so we have to exclude the auto-configuration of ollama when we are using openai and vice versa.
#Both model are used as you have configured both in POM, if not used it will through exception, so you have to exclude the one which you are not using, for example if you are using openai then you have to exclude ollama and vice versa.
